version: "3.9"

volumes:
  mysql:

services:
  mysql:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
  web:
    build:
      context: ./application
      dockerfile: ../container/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./application:/web-root
    ports:
      - "3000:3000"
    depends_on:
      - mysql
